version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
